[package]
name = "procmon"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "procmon"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.1"

[target.'cfg(target_os = "linux")'.dependencies]
cnproc = "0.2.1"
